---
application:
  name: "node-mvc"
  project: "node-mvc"
  organization: "QoveryCommunity"
databases:
- type: mongodb
  version: "4.4.4"
  name: node-nosql
routers:
- name: "main-node-mvc"
  routes:
  - application_name: "node-mvc"
    paths:
    - "/*"
