---
application:
  name: 'node-mvc'
  project: 'node_shop'
  organization: 'QoveryCommunity'
databases:
  - type: 'MONGODB'
    name: 'shop'
    version: '4.4.4'
routers:
  - name: 'main-node-mvc'
    routes:
      - application_name: 'node-mvc'
        paths:
          - '/*'
